pipeline:
  build-and-push:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: "madnificent/${CI_REPO_NAME%%-service}"
      tags: "feature-${CI_COMMIT_BRANCH##feature/}"
      platforms: linux/amd64
    secrets: [docker_username, docker_password]
when:
  event: push
  branch: feature/*
